aboutus_app/urls.py
from django.urls import path
from . import views

app_name = "aboutus_app"



urlpatterns = [
    path('about_us', views.abuotus, name='aboutus'),
]

account_app/urls.py
from django.urls import path
from . import views
from .views import EditView

app_name = 'account_app'

urlpatterns = [
    path('login', views.login_user, name='login'),
    path('register', views.register_user, name='register'),
    path('logout', views.log_out, name='logout'),
    path('profile/<int:pk>', views.profile, name='profile'),
    path('edit_profile', EditView.as_view(), name='edit'),
]

blogentries_app/urls.py
from django.urls import path
from . import views

app_name = "blogentries_app"



urlpatterns = [
    path('blogentries_app', views.blogentries, name='blogentries_app'),
    path('detail/<slug:slug>', views.detail, name='detail'),
    path('category_list/<int:pk>', views.category_list, name='category_list'),
    path('search/', views.search, name='search'),
    path('like/<slug:slug>/<int:pk>', views.like, name='like'),
]

contactus_app/urls.py
from django.urls import path
from . import views


app_name = 'contact'

urlpatterns = [
    path('contact', views.contact, name='contact'),
]

home_app/urls.py
from django.urls import path
from . import views


app_name = 'home_app'

urlpatterns = [
    path('', views.home, name='home'),
]

standgram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin_login/', admin.site.urls),
    path('', include('home_app.urls')),
    path('', include('aboutus_app.urls')),
    path('', include('blogentries_app.urls')),
    path('', include('contactus_app.urls')),
    path('', include('account_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'helpers.views.not_found'

templates/include/footer.html
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <ul class="social-icons">
              <li><a href="#">Facebook</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Behance</a></li>
              <li><a href="#">Linkedin</a></li>
              <li><a href="#">Dribbble</a></li>
            </ul>
          </div>
          <div class="col-lg-12">
            <div class="copyright-text">
              <p>Copyright 2020 Stand Blog Co.

                 | Design: <a rel="nofollow" href="https://templatemo.com" target="_parent">TemplateMo</a></p>
            </div>
          </div>
        </div>
      </div>
    </footer>

templates/include/header.html
<header class="">
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home_app:home' %}"><h2>Stand Blog<em>.</em></h2></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item {% if request.resolver_match.url_name == 'home' %} active {% endif %}">
                        <a class="nav-link" href="{% url 'home_app:home' %}">Home</a>
                    </li>
                    <li class="nav-item {% if request.resolver_match.url_name == 'aboutus' %} active {% endif %}">
                        <a class="nav-link" href="{% url 'aboutus_app:aboutus' %}">About Us</a>
                    </li>
                    <li class="nav-item {% if request.resolver_match.url_name == 'blogentries_app' %} active {% endif %}">
                        <a class="nav-link" href="{% url 'blogentries_app:blogentries_app' %}">Blog Entries</a>
                    </li>
                    <li class="nav-item {% if request.resolver_match.url_name == 'contact' %} active {% endif %}">
                        <a class="nav-link" href="{% url 'contact:contact' %}">Contact Us</a>
                    </li>
                    <li class="nav-item">
                        {% if request.user.is_authenticated %}
                            <a class="nav-link" href="{% url 'account_app:profile' user.id %}">{{ request.user.fullname }}</a>
                        {% else %}
                            <a class="nav-link" href="{% url 'account_app:login' %}">Login</a>
                        {% endif %}
                    </li>
                    <li class="nav-item">
                        {% if request.user.is_authenticated %}
                            <a class="nav-link" href="{% url 'account_app:logout' %}">logout</a>
                        {% endif %}
                    </li>
                                 <li class="nav-item">
                                        {% if request.user.is_anonymous %}
                                            <a class="nav-link" href="{% url 'account_app:register' %}">register</a>
                                        {% endif %}
                                  </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

templates/include/side_bar.html
<div class="col-lg-4">
    <div class="sidebar">
        <div class="row">
            <div class="col-lg-12">
                <div class="sidebar-item search">
                    <form id="search_form" name="gs" method="GET" action="{% url 'blogentries_app:search' %}">
                        <input type="text" name="q" class="searchText" placeholder="type to search..."
                               autocomplete="on">
                    </form>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="sidebar-item recent-posts">
                    <div class="sidebar-heading">
                        <h2>Most Liked Posts</h2>
                    </div>
                    <div class="content">
                        <ul>
                            <li><a href="">
                                <h5></h5>
                                <span></span>
                            </a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="sidebar-item recent-posts">
                    <div class="sidebar-heading">
                        <h2>Recent Posts</h2>
                    </div>
                    <div class="content">
                        <ul>
                            {% for item in recent_post %}
                                <li><a href="{{ item.get_absolute_url }}">
                                    <h5>{{ item.title }}</h5>
                                    <span>{{ item.date_published }}</span>
                                </a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="sidebar-item categories">
                    <div class="sidebar-heading">
                        <h2>Categories</h2>
                    </div>
                    <div class="content">
                        <ul>
                            {% for x in category %}
                                <li><a href="{% url 'blogentries_app:category_list' x.id %}">- {{ x.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="sidebar-item tags">
                    <div class="sidebar-heading">
                        <h2>Tag Clouds</h2>
                    </div>
                    <div class="content">
                        <ul>
                            <li><a href="#"> arash </a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>