account_app/urls.py
from django.urls import path
from . import views
from .views import EditView

app_name = 'account_app'

urlpatterns = [
    path('login', views.login_user, name='login'),
    path('register', views.register_user, name='register'),
    path('logout', views.log_out, name='logout'),
    path('profile/<int:pk>', views.profile, name='profile'),
    path('edit_profile', EditView.as_view(), name='edit'),
]

blogentries_app/urls.py
from django.urls import path
from . import views

app_name = "blogentries_app"



urlpatterns = [
    path('blogentries_app', views.blogentries, name='blogentries_app'),
    path('detail/<slug:slug>', views.detail, name='detail'),
    path('category_list/<int:pk>', views.category_list, name='category_list'),
    path('search/', views.search, name='search'),
    path('like/<slug:slug>/<int:pk>', views.like, name='like'),
]

home_app/urls.py
from django.urls import path
from . import views


app_name = 'home_app'

urlpatterns = [
    path('', views.home, name='home'),
]

standgram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin_login/', admin.site.urls),
    path('', include('home_app.urls')),
    path('', include('aboutus_app.urls')),
    path('', include('blogentries_app.urls')),
    path('', include('contactus_app.urls')),
    path('', include('account_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'helpers.views.not_found'

blogentries_app/models.py
from django.urls import reverse
from django.utils.text import slugify
from account_app.models import User
from django.db import models

# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=70)

    def __str__(self):
        return f"{self.title}"


class Post(models.Model):
    riter = models.ForeignKey(User, null=True, on_delete=models.SET_NULL,)
    category = models.ManyToManyField(Category)
    title = models.CharField(max_length=50, unique=True)
    body = models.TextField()
    date_published = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='images/post')
    slug = models.SlugField(unique=True, blank=True)

    class Meta:
        ordering = ('-date_published', 'updated',)

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        self.slug = slugify(self.title)
        super(Post,self).save()

    def get_absolute_url(self):
        return reverse('blogentries_app:detail', kwargs={'slug' : self.slug})


    def __str__(self):
        return f"{self.title}"


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')
    body = models.TextField()
    time_add_comment = models.DateTimeField(auto_now_add=True)




    def __str__(self):
        return self.body[:50]


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='likes')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='likes')


    def __str__(self):
        return f"{self.user.fullname} - {self.post.title}"

blogentries_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView
from blogentries_app.models import Post, Category, Comment, Like
from django.core.paginator import Paginator

# Create your views here.



def blogentries(request):
    post = Post.objects.all()
    page_number = request.GET.get('page')
    paginator = Paginator(post, 3)
    objects_list = paginator.get_page(page_number)
    context = {
        'post': objects_list
    }

    return render(request, 'blogentries_app/blog.html', context)


def detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.method == 'POST':
        parent_id = request.POST.get('parent_id')
        body = request.POST.get('body')
        Comment.objects.create(body=body, post=post, user=request.user, parent_id=int(parent_id))

    context = {
        'post': post
    }
    return render(request, 'blogentries_app/post-details.html', context)


def category_list(request, pk=None):
    category = get_object_or_404(Category, id=pk)

    post = category.post_set.all()

    context = {
        'post': post
    }
    return render(request, 'blogentries_app/blog.html', context)


def search(request):
    q = request.GET.get('q')
    post = Post.objects.filter(title__icontains=q)
    page_number = request.GET.get('page')
    paginator = Paginator(post, 3)
    objects_list = paginator.get_page(page_number)
    context = {
        'post': objects_list
    }
    return render(request, 'blogentries_app/blog.html', context)

def like(request, slug, pk):
    try:
        like = Like.objects.get(post__slug=slug, user_id=request.user.id)
        like.delete()
    except:
        Like.objects.create(post_id=pk, user_id=request.user.id)

    return redirect('blogentries_app:detail', slug,)

blogentries_app/templates/blogentries_app/blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <body>
    <div class="heading-page header-text">
    </div>
    <section class="blog-posts grid-system">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="all-blog-posts">
                        <div class="row">
                            {% for post in post %}
                                <div class="col-lg-6">
                                    <div class="blog-post">
                                        <div class="blog-thumb">
                                            <img src="{{ post.image.url }}" alt="">
                                        </div>
                                        <div class="down-content">
                                            <span>{{ post.category.all.0 }}</span>
                                            <a href="{{ post.get_absolute_url }}"><h4>{{ post.title }}</h4></a>
                                            <ul class="post-info">
                                                <li><a href="#">{{ post.riter.fullname }}</a></li>
                                                <li><a href="#">{{ post.date_published }}</a></li>
                                                <li><a href="#">Comment : {{ post.comments.count }}</a></li>
                                            </ul>
                                            <p>{{ post.body|truncatewords:50 }}</p>
                                            <div class="post-options">
                                                <div class="row">
                                                    <div class="col-lg-12">
                                                        <ul class="post-tags">
                                                            <li><i class="fa fa-tags"></i></li>
                                                            <li><a href="#">Best Templates</a>,</li>
                                                            <li><a href="#">TemplateMo</a></li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="col-lg-12">
                                {% if post.has_other_pages %}
                                    <ul class="page-numbers">
                                        {% if post.has_previous %}
                                            <li><a href="?page={{ post.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><i
                                                    class="fa fa-angle-double-left"></i></a></li>
                                        {% endif %}

                                        {% for i in post.paginator.page_range %}
                                            {% if post.number == i %}
                                                <li class="active"><a href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a></li>
                                            {% else %}
                                                <li><a href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a></li>
                                            {% endif %}
                                        {% endfor %}

                                        {% if post.has_next %}
                                            <li><a href="?page={{ post.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><i
                                                    class="fa fa-angle-double-right"></i></a></li>
                                        {% endif %}
                                    </ul>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                {% include 'include/side_bar.html' %}
            </div>
        </div>
    </section>
    </body>
{% endblock %}

blogentries_app/templates/blogentries_app/post-details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <body>
    <div class="heading-page header-text">
    </div>
    <section class="blog-posts grid-system">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="all-blog-posts">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="blog-post">
                                    <div class="blog-thumb">
                                        <img src="{{ post.image.url }}" alt="">
                                    </div>
                                    <div class="down-content">
                                        <span>{{ post.category.all.0 }}</span>
                                        <a href="post-details.html"><h4>{{ post.title }}</h4></a>
                                        <ul class="post-info">
                                            <li><a href="#">{{ post.riter.fullname }}</a></li>
                                            <li><a href="#">{{ post.date_published }}</a></li>
                                            <li><a href="#">Comment : {{ post.comments.count }}</a></li>
                                        </ul>
                                        <p>{{ post.body }}</p>
                                        <div class="post-options">
                                            <div class="row">
                                                <div class="col-6">
                                                    <ul class="post-tags">
                                                        <li>
                                                            <a href="{% url "blogentries_app:like" post.slug post.id %}">
                                                                <i style="font-size: 25px" class="fa fa-heart-o"> : {{ post.likes.count }}</i>
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </div>
                                                <div class="col-6">
                                                    <ul class="post-share">
                                                        <li><i class="fa fa-share-alt"></i></li>
                                                        <li><a href="#">Facebook</a>,</li>
                                                        <li><a href="#"> Twitter</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="sidebar-item comments">
                                    <div class="sidebar-heading">
                                        <h2>Comment : {{ post.comments.count }}</h2>
                                    </div>
                                    <div class="content">
                                        <ul>
                                            {% for comment in post.comments.all %}
                                                {% if comment.parent == None %}
                                                    <li>
                                                        <div class="author-thumb">
                                                            <img src="{% static 'images/profile1.png' %}" alt="">
                                                        </div>
                                                        <div class="right-content">
                                                            <h4>{{ comment.user.fullname }}<span>{{ comment.time_add_comment }}</span>
                                                            </h4>
                                                            <p>{{ comment.body }}</p>
                                                            <button type="submit" id="form-submit"
                                                                    class="btn btn-outline-warning"
                                                                    style="margin-top: 10px;margin-left: 500px;"
                                                                    onclick="set_value({{ comment.id }})">
                                                                Reply
                                                            </button>
                                                        </div>
                                                    </li>
                                                {% endif %}
                                                {% for rep in comment.replies.all %}
                                                    <li class="replied">
                                                        <div class="author-thumb">
                                                            <img src="{% static 'images/profile2.png' %}" alt="">
                                                        </div>
                                                        <div class="right-content">
                                                            <h4>{{ rep.user.fullname }}<span>{{ rep.time_add_comment }}</span>
                                                            </h4>
                                                            <p>{{ rep.body }}</p>
                                                        </div>
                                                    </li>
                                                {% endfor %}
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            {% if request.user.is_authenticated %}
                                <div class="col-lg-12">
                                <div class="sidebar-item submit-comment">
                                    <div class="sidebar-heading">
                                        <h2>Your comment</h2>
                                    </div>
                                    <div class="content">
                                        <form id="comment" action="#" method="post">
                                            {% csrf_token %}
                                            <div class="row">
                                                <input type="hidden" id="parent_id" name="parent_id" value="">
                                                <div class="col-lg-12">
                                                    <fieldset>
                                                            <textarea name="body" rows="6" id="body"
                                                                      placeholder="Type your comment"
                                                                      required=""></textarea>
                                                    </fieldset>
                                                </div>
                                                <div class="col-lg-12">
                                                    <fieldset>
                                                        <button type="submit" id="form-submit" class="main-button">
                                                            Submit
                                                        </button>
                                                    </fieldset>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            {% else %}
                                <div class="col-lg-12">
                                    <div class="main-button">
                                        <a href="{% url 'account_app:login' %}">You Not Login</a>
                                    </div>
                                </div>
                            {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    </body>
    <script>
        function set_value(id) {
            document.getElementById('parent_id').value = id;
            window.location.href = "#body"
        }

    </script>
{% endblock %}